init (task-24) : solution
miksturchik/js_pro-lesson-4 pull request #13
Opened 2022-05-19 08:02 UTC by miksturchik

2022-05-28 13:36 UTC, PaulVersAtile requested changes

2022-05-28 13:36 UTC, PaulVersAtile commented on src/TimePicker.tsx
> +                <h2>{hours === 0 ? "00" : hours}</h2>
Хотелось бы видеть числа в формате 01 , 02 , 03 и т.д. для чисел от 1 до 9

2022-06-04 09:52 UTC, miksturchik commented on src/TimePicker.tsx
> +                <h2>{hours === 0 ? "00" : hours}</h2>
done)

2022-06-08 11:09 UTC, PaulVersAtile approved these changes

2022-06-08 19:09 UTC, merged