init (task-23) : solution
miksturchik/js_pro-lesson-4 pull request #14
Opened 2022-05-22 15:41 UTC by miksturchik

2022-05-28 14:05 UTC, PaulVersAtile requested changes

2022-05-28 14:05 UTC, PaulVersAtile commented on src/RandomName.tsx
> +                        <div key={index}>
Не стоит использовать index в качестве key. Здесь надо подумать, как выкрутиться не используя index

2022-06-04 09:22 UTC, miksturchik commented on src/RandomName.tsx
> +                        <div key={index}>
поправила

2022-06-08 10:52 UTC, PaulVersAtile requested changes
Отписал коммент по имени интерфейса

2022-06-12 14:57 UTC, PaulVersAtile approved these changes

2022-06-14 13:15 UTC, merged